version: '3.7'
services:
    nginx:
        container_name: app-nginx
        image: nginx:latest
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www
        networks:
          - app
    php:
        container_name: app-php
        build:
            args:
              user: jonathan
              uid: 1000
            context: ./
            dockerfile: ./docker/php/Dockerfile
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www/
        volumes:
            - ./:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
          - app
    db:
        container_name: app-mysql
        image: mysql:5.7
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: app
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - dbdata:/var/lib/mysql/
            - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
        ports:
            - "3306:3306"
        networks:
          - app

networks:
  app:
    driver: bridge

volumes:
  dbdata:
    driver: local